<template>
  <div class="home">
    <!-- Hero Section -->
    <section class="hero-section">
      <div class="hero-container">
        <div class="hero-content">
          <div class="hero-badge">
            <svg class="badge-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M13 2L3 14H12L11 22L21 10H12L13 2Z" fill="currentColor"/>
            </svg>
            <span>AI-Powered CI/CD</span>
          </div>
          
          <h1 class="hero-title">
            간편한 <span class="gradient-text">CI/CD 자동화</span>
            <br />플랫폼
          </h1>
          
          <p class="hero-description">
            GitHub과 Google Cloud Platform을 연결하여
            <br />클릭 한 번으로 CI/CD 파이프라인을 설정하세요.
          </p>
          
          <div class="hero-actions">
            <router-link to="/login" class="btn btn-primary btn-lg">
              <svg class="btn-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M5 12H19M19 12L12 5M19 12L12 19" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
              지금 시작하기
            </router-link>
            <a href="#features" class="btn btn-secondary btn-lg">
              자세히 알아보기
            </a>
          </div>
          
          <div class="hero-stats">
            <div class="stat">
              <div class="stat-value">5분</div>
              <div class="stat-label">설정 시간</div>
            </div>
            <div class="stat-divider"></div>
            <div class="stat">
              <div class="stat-value">100%</div>
              <div class="stat-label">자동화</div>
            </div>
            <div class="stat-divider"></div>
            <div class="stat">
              <div class="stat-value">24/7</div>
              <div class="stat-label">모니터링</div>
            </div>
          </div>
        </div>
        
        <div class="hero-visual">
          <div class="visual-card">
            <div class="visual-header">
              <div class="visual-dots">
                <span class="dot"></span>
                <span class="dot"></span>
                <span class="dot"></span>
              </div>
              <span class="visual-title">main.yml</span>
            </div>
            <pre class="visual-code"><code><span class="code-keyword">name:</span> <span class="code-string">Deploy to Cloud Run</span>

<span class="code-keyword">on:</span>
  <span class="code-keyword">push:</span>
    <span class="code-keyword">branches:</span> [main]

<span class="code-keyword">jobs:</span>
  <span class="code-keyword">deploy:</span>
    <span class="code-keyword">runs-on:</span> ubuntu-latest
    <span class="code-keyword">steps:</span>
      - <span class="code-keyword">uses:</span> actions/checkout@v3
      - <span class="code-keyword">name:</span> <span class="code-string">Deploy to GCP</span>
        <span class="code-keyword">run:</span> |
          <span class="code-comment"># Auto-generated by CI/CD AI</span>
          gcloud run deploy</code></pre>
          </div>
          <div class="visual-floating visual-floating-1">
            <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M12 2L2 7V12C2 18 12 22 12 22S22 18 22 12V7L12 2Z" fill="currentColor" opacity="0.1"/>
              <path d="M12 2L2 7V12C2 18 12 22 12 22S22 18 22 12V7L12 2Z" stroke="currentColor" stroke-width="2"/>
            </svg>
          </div>
          <div class="visual-floating visual-floating-2">
            <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <circle cx="12" cy="12" r="10" fill="currentColor" opacity="0.1"/>
              <path d="M12 6V12L16 14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
            </svg>
          </div>
        </div>
      </div>
    </section>

    <!-- Features Section -->
    <section id="features" class="features-section">
      <div class="container">
        <div class="section-header">
          <h2 class="section-title">주요 기능</h2>
          <p class="section-subtitle">복잡한 CI/CD 설정을 간단하게 만들어드립니다</p>
        </div>
        
        <div class="features-grid">
          <div class="feature-card">
            <div class="feature-icon-wrapper">
              <svg class="feature-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M16 8L8 16M16 8L16 16M16 8L8 8" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            </div>
            <h3 class="feature-title">간편한 연동</h3>
            <p class="feature-description">GitHub과 GCP를 OAuth로 안전하게 연결합니다.</p>
          </div>
          
          <div class="feature-card">
            <div class="feature-icon-wrapper">
              <svg class="feature-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M13 2L3 14H12L11 22L21 10H12L13 2Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            </div>
            <h3 class="feature-title">빠른 설정</h3>
            <p class="feature-description">복잡한 설정 없이 클릭 몇 번으로 CI/CD를 구축합니다.</p>
          </div>
          
          <div class="feature-card">
            <div class="feature-icon-wrapper">
              <svg class="feature-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M5 12L5 6C5 5.44772 5.44772 5 6 5L18 5C18.5523 5 19 5.44772 19 6L19 12M5 12L12 19M5 12L12 5M19 12L12 19M19 12L12 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            </div>
            <h3 class="feature-title">자동 배포</h3>
            <p class="feature-description">코드 푸시만으로 Cloud Run에 자동 배포됩니다.</p>
          </div>
          
          <div class="feature-card">
            <div class="feature-icon-wrapper">
              <svg class="feature-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <rect x="3" y="3" width="18" height="18" rx="2" stroke="currentColor" stroke-width="2"/>
                <path d="M9 9L9 15" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                <path d="M12 12L12 15" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                <path d="M15 7L15 15" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
              </svg>
            </div>
            <h3 class="feature-title">실시간 모니터링</h3>
            <p class="feature-description">배포 상태를 실시간으로 확인하고 관리합니다.</p>
          </div>
          
          <div class="feature-card">
            <div class="feature-icon-wrapper">
              <svg class="feature-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 2L2 7V12C2 18 12 22 12 22S22 18 22 12V7L12 2Z" stroke="currentColor" stroke-width="2"/>
              </svg>
            </div>
            <h3 class="feature-title">보안 우선</h3>
            <p class="feature-description">안전한 OAuth 인증과 암호화된 비밀 관리</p>
          </div>
          
          <div class="feature-card">
            <div class="feature-icon-wrapper">
              <svg class="feature-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M13 10V3L4 14H11L11 21L20 10L13 10Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            </div>
            <h3 class="feature-title">AI 최적화</h3>
            <p class="feature-description">프로젝트에 맞는 최적의 CI/CD 설정 자동 생성</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Workflow Section -->
    <section class="workflow-section">
      <div class="container">
        <div class="section-header">
          <h2 class="section-title">작동 방식</h2>
          <p class="section-subtitle">4단계로 완성되는 간단한 CI/CD 설정</p>
        </div>
        
        <div class="workflow-timeline">
          <div class="timeline-line"></div>
          
          <div class="workflow-step">
            <div class="step-icon">
              <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M9 19C4.7 19 1 15.3 1 11C1 6.7 4.7 3 9 3C11.9 3 14.4 4.4 15.8 6.5C16.2 6.2 16.7 6 17.3 6C18.6 6 19.6 6.7 20.1 7.7C21.7 8.2 23 9.6 23 11.2C23 13.2 21.3 14.9 19.2 14.9L9 19Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
              <span class="step-number">1</span>
            </div>
            <div class="step-content">
              <h4>GitHub 연결</h4>
              <p>GitHub 계정을 연결하고 레포지토리를 선택합니다.</p>
            </div>
          </div>
          
          <div class="workflow-step">
            <div class="step-icon">
              <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 2L2 7V12C2 18 12 22 12 22S22 18 22 12V7L12 2Z" stroke="currentColor" stroke-width="2"/>
              </svg>
              <span class="step-number">2</span>
            </div>
            <div class="step-content">
              <h4>GCP 설정</h4>
              <p>Google Cloud 프로젝트를 연결하고 배포 설정을 입력합니다.</p>
            </div>
          </div>
          
          <div class="workflow-step">
            <div class="step-icon">
              <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M14 2H6C5.4 2 5 2.4 5 3V21C5 21.6 5.4 22 6 22H18C18.6 22 19 21.6 19 21V7L14 2Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M14 2V7H19" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
              <span class="step-number">3</span>
            </div>
            <div class="step-content">
              <h4>자동 구성</h4>
              <p>필요한 권한과 GitHub Actions를 자동으로 설정합니다.</p>
            </div>
          </div>
          
          <div class="workflow-step">
            <div class="step-icon">
              <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M13 2L3 14H12L11 22L21 10H12L13 2Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
              <span class="step-number">4</span>
            </div>
            <div class="step-content">
              <h4>배포 시작</h4>
              <p>코드를 푸시하면 자동으로 Cloud Run에 배포됩니다.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- CTA Section -->
    <section class="cta-section">
      <div class="container">
        <div class="cta-card">
          <h2 class="cta-title">지금 바로 시작하세요</h2>
          <p class="cta-description">
            복잡한 CI/CD 설정에 시간을 낭비하지 마세요.
            <br />AI가 도와드립니다.
          </p>
          <router-link to="/login" class="btn btn-primary btn-lg">
            무료로 시작하기
          </router-link>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { useRouter } from 'vue-router'

const router = useRouter()

const getStarted = () => {
  router.push('/login')
}
</script>

<style scoped>
/* Hero Section */
.hero-section {
  min-height: 100vh;
  display: flex;
  align-items: center;
  padding: var(--space-2xl) 0;
  background: linear-gradient(135deg, var(--bg-secondary) 0%, var(--bg-primary) 100%);
  position: relative;
  overflow: hidden;
}

.hero-section::before {
  content: '';
  position: absolute;
  top: -50%;
  right: -50%;
  width: 200%;
  height: 200%;
  background: radial-gradient(circle, var(--primary-light) 0%, transparent 70%);
  opacity: 0.1;
  animation: float 20s ease-in-out infinite;
}

@keyframes float {
  0%, 100% { transform: translate(0, 0) rotate(0deg); }
  33% { transform: translate(-30px, -30px) rotate(120deg); }
  66% { transform: translate(30px, -20px) rotate(240deg); }
}

.hero-container {
  max-width: 1280px;
  margin: 0 auto;
  padding: 0 var(--space-xl);
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: var(--space-2xl);
  align-items: center;
}

.hero-content {
  z-index: 10;
}

.hero-badge {
  display: inline-flex;
  align-items: center;
  gap: var(--space-xs);
  padding: var(--space-xs) var(--space-md);
  background: var(--primary-light);
  color: var(--primary);
  border-radius: 100px;
  font-size: 0.875rem;
  font-weight: 600;
  margin-bottom: var(--space-lg);
}

.badge-icon {
  width: 16px;
  height: 16px;
}

.hero-title {
  font-size: 3.5rem;
  font-weight: 700;
  line-height: 1.1;
  margin-bottom: var(--space-lg);
  letter-spacing: -0.02em;
}

.gradient-text {
  background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.hero-description {
  font-size: 1.25rem;
  color: var(--text-secondary);
  line-height: 1.7;
  margin-bottom: var(--space-xl);
}

.hero-actions {
  display: flex;
  gap: var(--space-md);
  margin-bottom: var(--space-2xl);
}

.btn-icon {
  width: 20px;
  height: 20px;
  margin-left: var(--space-xs);
}

.hero-stats {
  display: flex;
  align-items: center;
  gap: var(--space-lg);
}

.stat {
  text-align: center;
}

.stat-value {
  font-size: 2rem;
  font-weight: 700;
  color: var(--primary);
  margin-bottom: var(--space-xs);
}

.stat-label {
  font-size: 0.875rem;
  color: var(--text-secondary);
}

.stat-divider {
  width: 1px;
  height: 40px;
  background: var(--border-color);
}

/* Hero Visual */
.hero-visual {
  position: relative;
  z-index: 10;
}

.visual-card {
  background: var(--bg-primary);
  border: 1px solid var(--border-color);
  border-radius: var(--border-radius);
  box-shadow: var(--shadow-xl);
  overflow: hidden;
  transform: perspective(1000px) rotateY(-15deg);
  transition: transform 0.3s ease;
}

.hero-visual:hover .visual-card {
  transform: perspective(1000px) rotateY(-5deg);
}

.visual-header {
  background: var(--bg-tertiary);
  padding: var(--space-sm) var(--space-md);
  border-bottom: 1px solid var(--border-color);
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.visual-dots {
  display: flex;
  gap: var(--space-xs);
}

.dot {
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: var(--gray-400);
}

.dot:first-child { background: #ef4444; }
.dot:nth-child(2) { background: #f59e0b; }
.dot:nth-child(3) { background: #10b981; }

.visual-title {
  font-size: 0.875rem;
  color: var(--text-secondary);
  font-family: var(--font-mono);
}

.visual-code {
  padding: var(--space-lg);
  margin: 0;
  font-family: var(--font-mono);
  font-size: 0.875rem;
  line-height: 1.6;
  color: var(--text-primary);
}

.code-keyword { color: var(--primary); font-weight: 600; }
.code-string { color: var(--success); }
.code-comment { color: var(--text-tertiary); font-style: italic; }

.visual-floating {
  position: absolute;
  animation: floating 6s ease-in-out infinite;
}

.visual-floating-1 {
  top: -20px;
  right: -20px;
  width: 60px;
  height: 60px;
  color: var(--primary);
}

.visual-floating-2 {
  bottom: -30px;
  left: -30px;
  width: 80px;
  height: 80px;
  color: var(--secondary);
  animation-delay: -3s;
}

@keyframes floating {
  0%, 100% { transform: translateY(0); }
  50% { transform: translateY(-20px); }
}

/* Features Section */
.features-section {
  padding: var(--space-2xl) 0;
  background: var(--bg-primary);
}

.section-header {
  text-align: center;
  margin-bottom: var(--space-2xl);
}

.section-title {
  font-size: 2.5rem;
  font-weight: 700;
  margin-bottom: var(--space-md);
  letter-spacing: -0.02em;
}

.section-subtitle {
  font-size: 1.125rem;
  color: var(--text-secondary);
}

.features-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
  gap: var(--space-lg);
}

.feature-card {
  background: var(--bg-secondary);
  border: 1px solid var(--border-color);
  border-radius: var(--border-radius);
  padding: var(--space-xl);
  transition: all 0.3s ease;
}

.feature-card:hover {
  transform: translateY(-4px);
  box-shadow: var(--shadow-lg);
  border-color: var(--primary-light);
}

.feature-icon-wrapper {
  width: 56px;
  height: 56px;
  background: var(--primary-light);
  border-radius: var(--border-radius-sm);
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: var(--space-lg);
}

.feature-icon {
  width: 28px;
  height: 28px;
  color: var(--primary);
}

.feature-title {
  font-size: 1.25rem;
  font-weight: 600;
  margin-bottom: var(--space-sm);
}

.feature-description {
  color: var(--text-secondary);
  line-height: 1.6;
}

/* Workflow Section */
.workflow-section {
  padding: var(--space-2xl) 0;
  background: var(--bg-secondary);
}

.workflow-timeline {
  position: relative;
  padding: var(--space-xl) 0;
}

.timeline-line {
  position: absolute;
  left: 50%;
  top: 0;
  bottom: 0;
  width: 2px;
  background: var(--border-color);
  transform: translateX(-50%);
}

.workflow-step {
  display: flex;
  align-items: center;
  margin-bottom: var(--space-2xl);
  position: relative;
}

.workflow-step:nth-child(even) {
  flex-direction: row-reverse;
}

.workflow-step:last-child {
  margin-bottom: 0;
}

.step-icon {
  position: absolute;
  left: 50%;
  transform: translateX(-50%);
  width: 64px;
  height: 64px;
  background: var(--bg-primary);
  border: 2px solid var(--primary);
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 10;
}

.step-icon svg {
  width: 28px;
  height: 28px;
  color: var(--primary);
}

.step-number {
  position: absolute;
  bottom: -8px;
  right: -8px;
  width: 24px;
  height: 24px;
  background: var(--primary);
  color: white;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 0.875rem;
  font-weight: 600;
}

.step-content {
  width: calc(50% - 60px);
  background: var(--bg-primary);
  border: 1px solid var(--border-color);
  border-radius: var(--border-radius);
  padding: var(--space-lg);
  box-shadow: var(--shadow);
}

.workflow-step:nth-child(even) .step-content {
  margin-left: calc(50% + 60px);
}

.workflow-step:nth-child(odd) .step-content {
  margin-right: calc(50% + 60px);
  text-align: right;
}

.step-content h4 {
  font-size: 1.25rem;
  font-weight: 600;
  margin-bottom: var(--space-sm);
  color: var(--text-primary);
}

.step-content p {
  color: var(--text-secondary);
  line-height: 1.6;
  margin: 0;
}

/* CTA Section */
.cta-section {
  padding: var(--space-2xl) 0;
  background: var(--bg-primary);
}

.cta-card {
  background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);
  border-radius: var(--border-radius-lg);
  padding: var(--space-2xl);
  text-align: center;
  position: relative;
  overflow: hidden;
}

.cta-card::before {
  content: '';
  position: absolute;
  top: -50%;
  right: -50%;
  width: 200%;
  height: 200%;
  background: radial-gradient(circle, rgba(255,255,255,0.1) 0%, transparent 70%);
}

.cta-title {
  font-size: 2.5rem;
  font-weight: 700;
  color: white;
  margin-bottom: var(--space-md);
  position: relative;
}

.cta-description {
  font-size: 1.125rem;
  color: rgba(255,255,255,0.9);
  line-height: 1.6;
  margin-bottom: var(--space-xl);
  position: relative;
}

.cta-card .btn {
  position: relative;
}

/* Responsive */
@media (max-width: 1024px) {
  .hero-container {
    grid-template-columns: 1fr;
    text-align: center;
  }
  
  .hero-visual {
    max-width: 600px;
    margin: 0 auto;
  }
  
  .visual-card {
    transform: none;
  }
  
  .hero-visual:hover .visual-card {
    transform: none;
  }
  
  .workflow-step,
  .workflow-step:nth-child(even) {
    flex-direction: column;
  }
  
  .step-icon {
    position: relative;
    left: auto;
    transform: none;
    margin-bottom: var(--space-lg);
  }
  
  .step-content,
  .workflow-step:nth-child(even) .step-content,
  .workflow-step:nth-child(odd) .step-content {
    width: 100%;
    margin: 0;
    text-align: left;
  }
  
  .timeline-line {
    display: none;
  }
}

@media (max-width: 768px) {
  .hero-title {
    font-size: 2.5rem;
  }
  
  .hero-description {
    font-size: 1.125rem;
  }
  
  .hero-actions {
    flex-direction: column;
    width: 100%;
  }
  
  .hero-actions .btn {
    width: 100%;
    justify-content: center;
  }
  
  .features-grid {
    grid-template-columns: 1fr;
  }
  
  .section-title {
    font-size: 2rem;
  }
  
  .cta-title {
    font-size: 2rem;
  }
}
</style>