# .github/workflows/deploy-backend.yml
name: Deploy Backend to GCP

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:  # 수동 실행 가능

env:
  SERVICE_NAME: cicdai-backend
  REGION: asia-northeast3  # 서울 리전

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Google Cloud Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        source: ./backend
        region: ${{ env.REGION }}
        env_vars: |
          ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
          FRONTEND_URL=${{ secrets.FRONTEND_URL }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          GITHUB_CLIENT_ID=${{ secrets.GH_CLIENT_ID }}
          GITHUB_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}