name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BACKEND_IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/backend
  FRONTEND_IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

    - name: Build and Push Backend
      run: |
        docker build -t ${{ env.BACKEND_IMAGE }}:${{ github.sha }} ./backend
        docker push ${{ env.BACKEND_IMAGE }}:${{ github.sha }}

    - name: Build and Push Frontend
      run: |
        docker build -t ${{ env.FRONTEND_IMAGE }}:${{ github.sha }} ./frontend
        docker push ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

    - name: Deploy Backend to Cloud Run
      id: deploy-backend
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: cicdai-backend
        region: ${{ secrets.GCP_REGION }}
        image: ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
        memory: 512Mi
        cpu: 1
        port: 8000
        env_vars: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          REDIS_URL=${{ secrets.REDIS_URL }}

    - name: Deploy Frontend to Cloud Run
      id: deploy-frontend
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: cicdai-frontend
        region: ${{ secrets.GCP_REGION }}
        image: ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
        memory: 256Mi
        cpu: 1
        port: 80
        env_vars: |
          VITE_API_URL=${{ steps.deploy-backend.outputs.url }}

    - name: Show Output URLs
      run: |
        echo "Backend URL: ${{ steps.deploy-backend.outputs.url }}"
        echo "Frontend URL: ${{ steps.deploy-frontend.outputs.url }}"