# .github/workflows/deploy-backend.yml
name: Deploy Backend to GCP

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:  # 수동 실행 가능

env:
  SERVICE_NAME: cicdai-backend
  REGION: asia-northeast3  # 서울 리전
  # OAuth 환경변수
  GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
  GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
  # API Keys
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
  # URLs
  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Google Cloud Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        source: ./backend
        region: ${{ env.REGION }}
        flags: '--allow-unauthenticated'
        env_vars: |
          ANTHROPIC_API_KEY=${{ env.ANTHROPIC_API_KEY }}
          FRONTEND_URL=${{ env.FRONTEND_URL }}
          DATABASE_URL=${{ env.DATABASE_URL }}
          GITHUB_CLIENT_ID=${{ env.GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET=${{ env.GITHUB_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ env.GOOGLE_CLIENT_SECRET }}
    
    - name: Get Service URL and Update Environment
      run: |
        SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format 'value(status.url)')
        echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV
        
        # Update the service with its own URL
        gcloud run services update ${{ env.SERVICE_NAME }} \
          --region ${{ env.REGION }} \
          --update-env-vars BASE_URL=$SERVICE_URL
        
    - name: Show deployment info
      run: |
        echo "✅ Backend deployed successfully!"
        echo "🔗 Service URL: ${{ env.SERVICE_URL }}"
        echo ""
        echo "📝 OAuth Redirect URIs:"
        echo "GitHub: ${{ env.SERVICE_URL }}/api/auth/github/callback"
        echo "Google: ${{ env.SERVICE_URL }}/api/auth/google/callback"
