name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.GCP_REGION }}-docker.pkg.dev
  REPOSITORY: cicdai-repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    - name: Create Artifact Registry Repository
      run: |
        gcloud artifacts repositories create ${{ env.REPOSITORY }} \
          --repository-format=docker \
          --location=${{ secrets.GCP_REGION }} \
          --project=${{ secrets.GCP_PROJECT_ID }} || true

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/backend:${{ github.sha }} ./backend
        docker push ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/backend:${{ github.sha }}

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/frontend:${{ github.sha }} ./frontend
        docker push ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/frontend:${{ github.sha }}

    - name: Deploy Backend to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: cicdai-backend
        region: ${{ secrets.GCP_REGION }}
        image: ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/backend:${{ github.sha }}

    - name: Deploy Frontend to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: cicdai-frontend
        region: ${{ secrets.GCP_REGION }}
        image: ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/frontend:${{ github.sha }}

    - name: Show Output URLs
      run: |
        echo "Backend URL: $(gcloud run services describe cicdai-backend --region=${{ secrets.GCP_REGION }} --format='value(status.url)')"
        echo "Frontend URL: $(gcloud run services describe cicdai-frontend --region=${{ secrets.GCP_REGION }} --format='value(status.url)')"
