name: Build and Deploy

on:
  push:
    branches: [ main ]

env:
  BACKEND_SERVICE: backend
  FRONTEND_SERVICE: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    # Backend Service
    - name: Build Backend
      run: |
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/backend:${{ github.sha }} ./backend

    - name: Push Backend
      run: |
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/backend:${{ github.sha }}

    - name: Deploy Backend
      id: deploy-backend
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.BACKEND_SERVICE }}
        region: ${{ secrets.GCP_REGION }}
        image: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/backend:${{ github.sha }}
        env_vars: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          REDIS_URL=${{ secrets.REDIS_URL }}
        memory: 512Mi
        cpu: 1
        port: 8000

    # Frontend Service
    - name: Build Frontend
      run: |
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/frontend:${{ github.sha }} ./frontend

    - name: Push Frontend
      run: |
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/frontend:${{ github.sha }}

    - name: Deploy Frontend
      id: deploy-frontend
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.FRONTEND_SERVICE }}
        region: ${{ secrets.GCP_REGION }}
        image: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/frontend:${{ github.sha }}
        env_vars: |
          VITE_API_URL=${{ steps.deploy-backend.outputs.url }}
        memory: 256Mi
        cpu: 1
        port: 80

    - name: Output URLs
      run: |
        echo "Backend URL: ${{ steps.deploy-backend.outputs.url }}"
        echo "Frontend URL: ${{ steps.deploy-frontend.outputs.url }}"