name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BACKEND_SERVICE: cicdai-backend
  FRONTEND_SERVICE: cicdai-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Enable Cloud Run API
      run: gcloud services enable run.googleapis.com

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    - name: Create Artifact Registry Repository
      run: |
        gcloud artifacts repositories create cicdai-repo \
          --repository-format=docker \
          --location=${{ secrets.GCP_REGION }} \
          --quiet || true

    - name: Build & Push Backend
      run: |
        cd backend
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/backend:${{ github.sha }} .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/backend:${{ github.sha }}

    - name: Build & Push Frontend
      run: |
        cd frontend
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/frontend:${{ github.sha }} .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/frontend:${{ github.sha }}

    - name: Deploy Backend to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.BACKEND_SERVICE }}
        region: ${{ secrets.GCP_REGION }}
        image: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/backend:${{ github.sha }}
        flags: '--allow-unauthenticated --port=8000 --memory=512Mi --cpu=1'
        env_vars: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          REDIS_URL=${{ secrets.REDIS_URL }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET=${{ secrets.GITHUB_CLIENT_SECRET }}

    - name: Deploy Frontend to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.FRONTEND_SERVICE }}
        region: ${{ secrets.GCP_REGION }}
        image: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/frontend:${{ github.sha }}
        flags: '--allow-unauthenticated --port=80 --memory=512Mi --cpu=1'

    - name: Show Output URLs
      run: |
        echo "Backend URL: $(gcloud run services describe ${{ env.BACKEND_SERVICE }} --region ${{ secrets.GCP_REGION }} --format 'value(status.url)')"
        echo "Frontend URL: $(gcloud run services describe ${{ env.FRONTEND_SERVICE }} --region ${{ secrets.GCP_REGION }} --format 'value(status.url)')"
