name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.GCP_REGION }}-docker.pkg.dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Create Artifact Registry Repository
        run: |
          gcloud artifacts repositories create cicdai-repo \
            --repository-format=docker \
            --location=${{ secrets.GCP_REGION }} \
            --quiet || true

      - name: Build and Push Backend
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/backend:${{ github.sha }} ./backend
          docker push ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/backend:${{ github.sha }}

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/frontend:${{ github.sha }} ./frontend
          docker push ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/frontend:${{ github.sha }}

      - name: Deploy Backend to Cloud Run
        id: deploy-backend
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: cicdai-backend
          image: ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/backend:${{ github.sha }}
          region: ${{ secrets.GCP_REGION }}
          flags: --allow-unauthenticated --port=8000
          env_vars: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            REDIS_URL=${{ secrets.REDIS_URL }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}
          memory: 512Mi
          cpu: 1

      - name: Deploy Frontend to Cloud Run
        id: deploy-frontend
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: cicdai-frontend
          image: ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/frontend:${{ github.sha }}
          region: ${{ secrets.GCP_REGION }}
          flags: --allow-unauthenticated --port=80
          memory: 512Mi
          cpu: 1

      - name: Show Output URLs
        run: |
          echo "Backend URL: ${{ steps.deploy-backend.outputs.url }}"
          echo "Frontend URL: ${{ steps.deploy-frontend.outputs.url }}"
