name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  FRONTEND_IMAGE: frontend-image
  BACKEND_IMAGE: backend-image
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}

      - name: Create Artifact Registry Repository if not exists
        run: |
          gcloud artifacts repositories create cicdai-repo \
            --repository-format=docker \
            --location=${{ env.GCP_REGION }} \
            --description="CI/CD AI Docker repository" || true

      - name: Build Frontend
        working-directory: frontend
        run: |
          docker build -t ${{ env.GAR_LOCATION }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/${{ env.FRONTEND_IMAGE }}:${{ github.sha }} .
          docker push ${{ env.GAR_LOCATION }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

      - name: Build Backend
        working-directory: backend
        run: |
          docker build -t ${{ env.GAR_LOCATION }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/${{ env.BACKEND_IMAGE }}:${{ github.sha }} .
          docker push ${{ env.GAR_LOCATION }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/${{ env.BACKEND_IMAGE }}:${{ github.sha }}

      - name: Deploy Frontend to Cloud Run
        id: deploy-frontend
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: cicdai-frontend
          image: ${{ env.GAR_LOCATION }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          region: ${{ env.GCP_REGION }}
          flags: --port=80 --allow-unauthenticated

      - name: Deploy Backend to Cloud Run
        id: deploy-backend
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: cicdai-backend
          image: ${{ env.GAR_LOCATION }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          region: ${{ env.GCP_REGION }}
          flags: --port=8000 --allow-unauthenticated
          env_vars: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            REDIS_URL=${{ secrets.REDIS_URL }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}
            GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }}
            GITHUB_CLIENT_SECRET=${{ secrets.GITHUB_CLIENT_SECRET }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}

      - name: Show URLs
        run: |
          echo "Frontend URL: ${{ steps.deploy-frontend.outputs.url }}"
          echo "Backend URL: ${{ steps.deploy-backend.outputs.url }}"