name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.GCP_REGION }}-docker.pkg.dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Create Artifact Registry Repository
        run: |
          gcloud artifacts repositories create cicdai-repo \
            --repository-format=docker \
            --location=${{ secrets.GCP_REGION }} \
            --quiet || true

      - name: Build and Push Backend
        working-directory: ./backend
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/backend:${{ github.sha }} .
          docker push ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/backend:${{ github.sha }}

      - name: Build and Push Frontend
        working-directory: ./frontend
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/frontend:${{ github.sha }} .
          docker push ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/cicdai-repo/frontend:${{ github.sha }}
